// Package openapi turns a loaded apigw config into a minimal
// OpenAPI 3.0 specification. The reverse of cmd/api/openapiimport.
//
// The export is deliberately minimal — apigw doesn't know individual
// path operations the way an OpenAPI-first design does, so we
// represent each API as a single `/{path}/{proxy+}` operation with
// `any` method support. Operators who want a real spec hand-edit
// the export or generate it from their upstream's annotations.
package openapi

import (
	"fmt"
	"sort"
	"time"
)

// Spec is the minimal OpenAPI 3.0 root we emit. Encoded as
// JSON/YAML by the caller (we don't pull in a YAML lib).
type Spec struct {
	OpenAPI    string              `json:"openapi" yaml:"openapi"`
	Info       Info                `json:"info" yaml:"info"`
	Servers    []Server            `json:"servers,omitempty" yaml:"servers,omitempty"`
	Paths      map[string]PathItem `json:"paths" yaml:"paths"`
	Components *Components         `json:"components,omitempty" yaml:"components,omitempty"`
	Tags       []Tag               `json:"tags,omitempty" yaml:"tags,omitempty"`
}

type Info struct {
	Title       string `json:"title" yaml:"title"`
	Version     string `json:"version" yaml:"version"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

type Server struct {
	URL         string `json:"url" yaml:"url"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

type PathItem struct {
	Get    *Operation `json:"get,omitempty" yaml:"get,omitempty"`
	Put    *Operation `json:"put,omitempty" yaml:"put,omitempty"`
	Post   *Operation `json:"post,omitempty" yaml:"post,omitempty"`
	Delete *Operation `json:"delete,omitempty" yaml:"delete,omitempty"`
	Patch  *Operation `json:"patch,omitempty" yaml:"patch,omitempty"`
}

type Operation struct {
	Tags        []string               `json:"tags,omitempty" yaml:"tags,omitempty"`
	Summary     string                 `json:"summary,omitempty" yaml:"summary,omitempty"`
	OperationID string                 `json:"operationId,omitempty" yaml:"operationId,omitempty"`
	Responses   map[string]ResponseRef `json:"responses" yaml:"responses"`
	Security    []map[string][]string  `json:"security,omitempty" yaml:"security,omitempty"`
	Deprecated  bool                   `json:"deprecated,omitempty" yaml:"deprecated,omitempty"`
}

type ResponseRef struct {
	Description string `json:"description" yaml:"description"`
}

type Components struct {
	SecuritySchemes map[string]SecurityScheme `json:"securitySchemes,omitempty" yaml:"securitySchemes,omitempty"`
}

// SecurityScheme is a tiny subset of OpenAPI's discriminated-union
// type. We only emit the shapes apigw can actually represent.
type SecurityScheme struct {
	Type         string `json:"type" yaml:"type"`                                     // apiKey | http | oauth2 | openIdConnect
	Scheme       string `json:"scheme,omitempty" yaml:"scheme,omitempty"`             // bearer (for http)
	BearerFormat string `json:"bearerFormat,omitempty" yaml:"bearerFormat,omitempty"` // JWT
	In           string `json:"in,omitempty" yaml:"in,omitempty"`                     // header | query (for apiKey)
	Name         string `json:"name,omitempty" yaml:"name,omitempty"`                 // header name (for apiKey)
	Description  string `json:"description,omitempty" yaml:"description,omitempty"`
}

type Tag struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

// API is the subset of config.API the exporter needs. Mirrored here
// so internal/openapi doesn't import internal/config (keeps the
// package re-usable and the dep graph clean).
type API struct {
	Name       string
	Path       string
	Enabled    bool
	HasAPIKey  bool
	APIKeyName string // header name; default "X-API-Key" when empty
	HasJWT     bool
	HasOAuth2  bool
	HasHMAC    bool
	HasMTLS    bool
	Deprecated bool // lifecycle.state == "deprecated"
	Retired    bool // skipped from export (410'd anyway)
}

// Export builds the Spec. title/version come from the caller — we
// don't synthesise from config because operators want stable
// per-release versions.
func Export(apis []API, title, version, baseURL string) Spec {
	spec := Spec{
		OpenAPI: "3.0.3",
		Info: Info{
			Title:       title,
			Version:     version,
			Description: fmt.Sprintf("Generated by apigw at %s", time.Now().UTC().Format(time.RFC3339)),
		},
		Paths: map[string]PathItem{},
	}
	if baseURL != "" {
		spec.Servers = []Server{{URL: baseURL}}
	}

	// Stable tag order — operators read this for diffs.
	sorted := append([]API(nil), apis...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	schemes := map[string]SecurityScheme{}
	for _, a := range sorted {
		if !a.Enabled || a.Retired {
			continue
		}
		path := a.Path
		if path == "" {
			path = "/api/" + a.Name
		}
		// One catch-all operation per method we usually expect.
		op := func(method string) *Operation {
			return &Operation{
				Tags:        []string{a.Name},
				Summary:     method + " on " + a.Name,
				OperationID: a.Name + "_" + method,
				Responses: map[string]ResponseRef{
					"200": {Description: "OK"},
				},
				Security:   securityFor(a, schemes),
				Deprecated: a.Deprecated,
			}
		}
		spec.Paths[path] = PathItem{
			Get:    op("get"),
			Post:   op("post"),
			Put:    op("put"),
			Delete: op("delete"),
			Patch:  op("patch"),
		}
		spec.Tags = append(spec.Tags, Tag{
			Name:        a.Name,
			Description: "API: " + a.Name,
		})
	}
	if len(schemes) > 0 {
		spec.Components = &Components{SecuritySchemes: schemes}
	}
	return spec
}

// securityFor returns the OpenAPI security requirement list for one
// API and registers the corresponding scheme in `schemes` (so the
// caller emits each scheme exactly once under components).
func securityFor(a API, schemes map[string]SecurityScheme) []map[string][]string {
	var req []map[string][]string
	if a.HasAPIKey {
		schemes["apigw_apikey"] = SecurityScheme{
			Type:        "apiKey",
			In:          "header",
			Name:        apikeyHeader(a.APIKeyName),
			Description: "apigw API key",
		}
		req = append(req, map[string][]string{"apigw_apikey": {}})
	}
	if a.HasJWT {
		schemes["apigw_jwt"] = SecurityScheme{
			Type:         "http",
			Scheme:       "bearer",
			BearerFormat: "JWT",
		}
		req = append(req, map[string][]string{"apigw_jwt": {}})
	}
	if a.HasOAuth2 {
		schemes["apigw_oauth2"] = SecurityScheme{
			Type:   "http",
			Scheme: "bearer",
		}
		req = append(req, map[string][]string{"apigw_oauth2": {}})
	}
	if a.HasHMAC {
		schemes["apigw_hmac"] = SecurityScheme{
			Type:        "http",
			Scheme:      "hmac",
			Description: "Authorization: HMAC <key-id>:<base64-sig>",
		}
		req = append(req, map[string][]string{"apigw_hmac": {}})
	}
	if a.HasMTLS {
		schemes["apigw_mtls"] = SecurityScheme{
			Type:        "mutualTLS",
			Description: "Client TLS certificate required",
		}
		req = append(req, map[string][]string{"apigw_mtls": {}})
	}
	return req
}

func apikeyHeader(name string) string {
	if name == "" {
		return "X-API-Key"
	}
	return name
}
